version: '3.8'

services:
  redis-cache:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-cache:/data

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "1234"

  backend-server:
    container_name: backend-server
    build:
      context: backend
      target: development
    tty: true
    restart: unless-stopped
    ports: [ "8080:8080" ]
    volumes:
      - ./backend/app:/backend/app:cached,ro
    env_file: [ ./backend/.env ]
    command: npm run dev #This will override the command in the Dockerfile
    depends_on: [ "mongodb", "redis-cache" ]
    environment:
      REDIS_HOST: "redis-cache"
      REDIS_PORT: 6379
      REDIS_PASSWORD: "123@p@ass"

  protein-frontend:
    container_name: protein-frontend
    build: frontend
    tty: true
    restart: unless-stopped
    ports: [ "5173:5173" ]
    volumes:
      - ./frontend/public:/frontend/public:cached,ro
      - ./frontend/src:/frontend/src:cached,ro
    depends_on: [ "backend-server" ]

volumes:
  redis-cache:
    driver: local
