version: '3.8'

services:
  redis-cache:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-cache:/data

  mongodb-server:
    image: mongo:4.4
    container_name: mongodb-server
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "1234"

  protein-backend:
    container_name: protein-backend
    build:
      context: backend
      target: production
    tty: true
    restart: unless-stopped
    ports: [ "8080:8080" ]
    volumes:
      - ./backend/app:/backend/app:cached,ro
    env_file: [ ./backend/.env ]
    depends_on: [ "mongodb-server", "redis-cache" ]
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: "redis-cache"
      REDIS_USERNAME: "protein"
      REDIS_PASSWORD: "protein-12345"

  protein-frontend:
    container_name: protein-frontend
    build: frontend
    tty: true
    restart: unless-stopped
    ports: [ "5173:5173" ]
    volumes:
      - ./frontend/public:/frontend/public:cached,ro
      - ./frontend/src:/frontend/src:cached,ro
    depends_on: [ "protein-backend" ]

volumes:
  redis-cache:
    driver: local
