# Generated by Django 4.2.3 on 2023-07-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnasequence',
            name='base',
            field=models.TextField(default='+'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnasequence',
            name='nucleotide_type',
            field=models.CharField(choices=[('D', 'DNA'), ('R', 'RNA')], default='D', max_length=4),
        ),
        migrations.AddField(
            model_name='dnasequence',
            name='schema',
            field=models.CharField(default='+', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnasequence',
            name='topology',
            field=models.CharField(choices=[('C', 'Circular'), ('L', 'Linear')], default='C', max_length=10),
        ),
    ]
