# Generated by Django 4.2.3 on 2023-07-29 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0002_dnasequence_base_dnasequence_nucleotide_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnasequence',
            old_name='owner',
            new_name='user_id',
        ),
    ]
