# Generated by Django 4.2.3 on 2023-10-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0003_rename_owner_dnasequence_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnasequence',
            name='schema',
        ),
    ]
