# Generated by Django 4.2.6 on 2023-10-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0004_remove_dnasequence_schema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnasequence',
            old_name='base',
            new_name='bases',
        ),
        migrations.AlterField(
            model_name='dnasequence',
            name='topology',
            field=models.CharField(choices=[('C', 'Circular'), ('L', 'Linear'), ('B', 'Both'), ('B_F', 'Both Flip')], default='C', max_length=10),
        ),
    ]
