# Generated by Django 4.2.6 on 2023-10-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0005_rename_base_dnasequence_bases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnasequence',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
