# Generated by Django 4.2.6 on 2023-10-11 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0006_alter_dnasequence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnasequence',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
