# Generated by Django 4.2.6 on 2023-10-12 16:12

from django.db import migrations, models
import sequence.models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0007_alter_dnasequence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnasequence',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[sequence.models.validate_string]),
        ),
    ]
