# Generated by Django 4.2.6 on 2023-10-12 16:16

from django.db import migrations, models
import sequence.models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0008_alter_dnasequence_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnasequence',
            name='description',
            field=models.TextField(blank=True, error_messages={'required': 'Enter a valid description'}, null=True, validators=[sequence.models.validate_string]),
        ),
    ]
