# Generated by Django 4.2.6 on 2023-10-13 10:10

from django.db import migrations, models
import sequence.models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0010_alter_dnasequence_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnasequence',
            name='name',
            field=models.CharField(max_length=100, validators=[sequence.models.validate_string, sequence.models.validate_no_emoji]),
        ),
    ]
