# Generated by Django 4.2.6 on 2023-10-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0012_alter_dnasequence_bases_alter_dnasequence_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnasequence',
            name='sequence',
        ),
    ]
