# Generated by Django 4.2.6 on 2023-10-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0013_remove_dnasequence_sequence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
    ]
