# Generated by Django 4.2.6 on 2023-10-23 18:15

from django.db import migrations, models
import dna_sequence.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNASequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=5, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('date_of_submission', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nucleotide_type', models.CharField(choices=[('D', 'DNA'), ('R', 'RNA')], default='D', max_length=4)),
                ('topology', models.CharField(choices=[('C', 'Circular'), ('L', 'Linear'), ('B', 'Both'), ('B_F', 'Both Flip')], default='C', max_length=10)),
                ('bases', models.TextField(blank=True, null=True, validators=[dna_sequence.models.validate_no_emoji])),
                ('name', models.CharField(max_length=100, validators=[dna_sequence.models.validate_no_emoji])),
                ('description', models.TextField(blank=True, error_messages={'required': 'Enter a valid description'}, null=True, validators=[dna_sequence.models.validate_no_emoji])),
            ],
            options={
                'ordering': ['date_of_submission'],
            },
        ),
        migrations.CreateModel(
            name='UploadFileForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
