# Generated by Django 4.2.6 on 2023-11-08 19:13

from django.db import migrations, models
import dna_sequence.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedUsers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='DNASequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('sequence_id', models.CharField(blank=True, max_length=20, null=True)),
                ('sequence', models.TextField(blank=True, null=True)),
                ('date_of_submission', models.DateTimeField(auto_now_add=True)),
                ('author_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nucleotide_type', models.CharField(choices=[('D', 'DNA'), ('R', 'RNA')], default='D', max_length=4)),
                ('topology', models.CharField(choices=[('C', 'Circular'), ('L', 'Linear'), ('B', 'Both'), ('B_F', 'Both Flip')], default='C', max_length=10)),
                ('bases', models.TextField(blank=True, null=True, validators=[dna_sequence.models.validate_no_emoji])),
                ('name', models.CharField(max_length=100, validators=[dna_sequence.models.validate_no_emoji])),
                ('description', models.TextField(blank=True, error_messages={'required': 'Enter a valid description'}, null=True, validators=[dna_sequence.models.validate_no_emoji])),
                ('invited_users', models.ManyToManyField(blank=True, related_name='invited_users', to='dna_sequence.invitedusers')),
            ],
            options={
                'ordering': ['-date_of_submission'],
            },
        ),
    ]
