# Generated by Django 4.2.6 on 2023-10-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_sequence', '0002_delete_uploadfileform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnasequence',
            options={'ordering': ['-date_of_submission']},
        ),
        migrations.AddField(
            model_name='dnasequence',
            name='sequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dnasequence',
            name='sequence_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
