# Generated by Django 4.2.6 on 2023-10-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dna_sequence', '0003_alter_dnasequence_options_dnasequence_sequence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnasequence',
            name='role',
        ),
    ]
