# Generated by Django 4.2.6 on 2023-11-05 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dna_sequence', '0004_remove_dnasequence_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedUsers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.RenameField(
            model_name='dnasequence',
            old_name='user_id',
            new_name='author_id',
        ),
        migrations.AddField(
            model_name='dnasequence',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_users', to='dna_sequence.invitedusers'),
        ),
    ]
