version: "3.8"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      DATABASE_URL: "mysql://root:password@mysql:3306/User"
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local