version: '3.8'

networks:
  bioseq-networks:

services:
  redis-cache:
    container_name: redis-server
    image: redis:alpine
    restart: always
    networks:
      - bioseq-networks
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-cache:/data

  mongodb-server:
    image: mongo:4.4
    container_name: mongodb-server
    networks:
      - bioseq-networks
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "1234"

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - bioseq-networks
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      DATABASE_URL: "mysql://root:password@mysql:3306/User"
 
  mysql2:
    container_name: mysql2
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - bioseq-networks
    environment:
      MYSQL_DATABASE: "DnaSequence"
      MYSQL_ROOT_PASSWORD: "RootPass"

  user-service:
    container_name: user-service
    build:
      context: ../user-service
      target: production
    tty: true
    restart: unless-stopped
    ports: [ "7070:7070" ]
    networks:
      - bioseq-networks
    volumes:
      - ../user-service/app:/user-service/app:cached
      - ../user-service/views:/user-service/views:cached
      - ../user-service/prisma:/user-service/prisma:cached
      - migrations:/user-service/prisma/migrations
      - /user-service/node_modules
    env_file: [ ../user-service/.env ]
    depends_on: [ "mysql" ]

  protein-analyzer:
    container_name: protein-analyzer
    build:
      context: ../protein-analyzer
      target: production
    tty: true
    restart: unless-stopped
    ports: [ "8080:8080" ]
    networks:
      - bioseq-networks
    volumes:
      - ../protein-analyzer/app:/protein-analyzer/app:cached,ro
      - /protein-analyzer/node_modules
    env_file: [ ../protein-analyzer/.env ]
    depends_on: [ "mongodb-server", "redis-cache" ]
    environment:
      REDIS_PORT: 6379
      REDIS_HOST: "redis-cache"
      REDIS_USERNAME: "protein"
      REDIS_PASSWORD: "protein-12345"

  dna-sequence:
    container_name: dna-Sequence
    build:
      context: ../dna-sequence
      dockerfile: ../dna-sequence/Dockerfile
    volumes:
      - ../dna-sequence:/app:cached
      - ../dna-sequence/dna_sequence/migrations:/app/dna_sequence/migrations:cached
    networks:
      - bioseq-networks
    restart: unless-stopped
    ports: [ "8000:8000" ]
    env_file: [ ../dna-sequence/.env ]
    depends_on: [ "mysql2" ]

  api-gateway:
    container_name: api-gateway
    build:
      context: ../api-gateway
      target: production
    tty: true
    restart: unless-stopped
    ports: [ "9090:9090" ]
    networks:
      - bioseq-networks
    volumes:
      - ../api-gateway/app:/api-gateway/app:cached
      - /api-gateway/node_modules
    env_file: [ ../api-gateway/.env ]
    depends_on:
      - protein-analyzer
      - dna-sequence
      - user-service

  client:
    container_name: client
    build: ../client
    tty: true
    restart: unless-stopped
    ports: [ "5173:5173" ]
    networks:
      - bioseq-networks
    volumes:
      - ../client/public:/client/public:cached,ro
      - ../client/src:/client/src:cached,ro
    env_file: [ ../client/.env ]
    depends_on: [ "protein-analyzer", "dna-sequence", "user-service" ]

volumes:
  redis-cache:
    driver: local
  migrations:
    driver: local
